[workspace]
members = ["compute-pcrs", "crds", "operator", "manifest-gen"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.99"
env_logger = "0.11.8"
clap = "4.5.41"
json-patch = "4.0.0"
jsonptr = "0.7.1"
k8s-openapi = "0.25.0"
kube = "1.1.0"
log = "0.4.27"
serde = "1.0.219"
serde_json = "1.0.141"
tokio = "1.46.1"
