[package]
name = "crds"
version = "0.1.0"
edition.workspace = true

[dependencies]
k8s-openapi.workspace = true
kube = { workspace = true, features = ["derive"] }
schemars = { version = "0.8", features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
